POST http://{{host}}/api/v1/change-password/{{token}}
Accept: application/json
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "password_confirmation": "{{password_confirmation}}"
}
