name: Deploy to AWS ECS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ct_project:latest --file docker/php-fpm/Dockerfile .
          docker tag ct_project:latest ${{ secrets.AWS_REGISTRY_URL }}/ct_project:latest
          docker push ${{ secrets.AWS_REGISTRY_URL }}/ct_project:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ct_project --service ct_project_service --force-new-deploy
