name: Docker Image CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build \
            --file docker/php-fpm/Dockerfile \
            --build-arg GROUP_ID=${{ secrets.GROUP_ID }} \
            --build-arg USER_ID=${{ secrets.USER_ID }} \
            --build-arg ENVIRONMENT=${{ secrets.ENVIRONMENT }} \
            --tag my-image-name:$(date +%s) .
