name: Docker Image CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build \
          --file docker/php-fpm/Dockerfile \
          --build-arg GROUP_ID=1000 \
          --build-arg USER_ID=1000 \
          --build-arg ENVIRONMENT=production \
          --tag my-image-name:$(date +%s) .
